{{- if and .Values.clefSettings.password (not .Values.clefSettings.existingPasswordSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bee.fullname" . }}-clefpassword
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bee.labels" . | nindent 4 }}
type: Opaque
data:
    password: {{ include "bee.clefPassword" . | b64enc | quote }}

{{- end -}}
