{{- if and .Values.libp2pSettings.enabled (not .Values.libp2pSettings.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bee.fullname" . }}-libp2p
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bee.labels" . | nindent 4 }}
type: Opaque
stringData:
  libp2pKeys: |-
    {{- range $key, $val := .Values.libp2pSettings.libp2pKeys }}
    {{ $key }}: {{ $val }}
    {{- end }}

{{- end -}}
