{{- if and .Values.clefSettings.enabled (not .Values.clefSettings.existingSecret) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bee.fullname" . }}-clef
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bee.labels" . | nindent 4 }}
type: Opaque
stringData:
  clefKeys: |-
    {{- range $key, $val := .Values.clefSettings.clefKeys }}
    {{ $key }}: {{ $val }}
    {{- end }}
    
{{- end -}}
