{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bee.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bee.labels" . | nindent 4 }}
--- 
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bee.serviceAccountName" . }}-ClusterRole
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","get", "update", "watch", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create","get", "list"]
  - apiGroups: ["alibabacloud.com"]
    resources: ["poddnats", "poddnats/status"]
    verbs: ["*"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create","update", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bee.serviceAccountName" . }}-ClusterRoleBinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bee.serviceAccountName" . }}-ClusterRole
subjects:
  - kind: ServiceAccount
    name: {{ include "bee.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
